version: "3"
services:
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  backend:
    build: 
      context: ./docker-back
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./docker-back:/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: 
      context: ./docker-front
    command: npm start
    volumes:
      - ./docker-front/:/frontend
    ports:
      - "8090:8090"
    depends_on:
      - backend
      - db
